import Navigation from "@/components/Navigation";
import "./globals.css";
import type { Metadata } from "next";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { Database } from "../../types/supabase";
import { cookies } from "next/headers";
import { GeistSans, GeistMono } from 'geist/font'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });
  const { data: { session } } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navigation session={session}/>
        <div className="mx-auto max-w-screen-xl min-h-screen px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
